import 'dart:convert';

import 'package:mockondo/core/interpolation.dart';
import 'package:mockondo/core/mock_model.dart';
import 'package:shelf/shelf.dart' as shelf;

/// Generates paginated response data for endpoints that have a pagination rule.
class GenerateCore {
  /// Builds a paginated response body for [request].
  ///
  /// The [pagination] rule supplies configuration through its `rules` map:
  ///   - `max`          — total number of items available
  ///   - `limit_param`  — query parameter name for the page size (e.g. `"limit"`)
  ///   - `offset_param` — query parameter name for the page number (e.g. `"page"`)
  ///
  /// Items for the current page are generated by running interpolation on
  /// [pagination.response] with `data` set to the item's absolute index.
  /// The resulting list is then injected into [responseBody] via
  /// `${pagination.data}`.
  ///
  /// Returns an empty list when the requested page is beyond [max].
  static String pagination({
    required shelf.Request request,
    required String responseBody,
    Rules? pagination,
  }) {
    final generatePagination = <String>[];

    final max = int.parse((pagination?.rules['max'] ?? '0').toString());
    final limit = int.parse(
      request.url.queryParameters[pagination?.rules['limit_param']] ?? '0',
    );

    // `offset_param` holds the page number (1-based); multiply by limit to get
    // the absolute item offset.
    final offset = int.parse(
      request.url.queryParameters[pagination?.rules['offset_param']] ?? '0',
    );

    if (pagination != null) {
      final maxLoop = limit * offset;

      // Return an empty array when the page is out of range.
      if (maxLoop > max) {
        final encoded = jsonEncode(generatePagination);
        return Interpolation().excute(
          before: responseBody,
          data: encoded,
          request: request,
        );
      }

      // Generate each item for the current page.
      for (var i = 0; i < limit; i++) {
        // Pass the absolute index as `data` so `${random.index}` returns the
        // correct value for each item in the page.
        var decode = jsonDecode(
          Interpolation().excute(
            before: pagination.response,
            data: '${(limit * offset) + i}',
            request: request,
          ),
        );
        generatePagination.add(jsonEncode(decode));
      }
    }

    // Parse each item back to a Dart object so jsonEncode produces a proper
    // JSON array rather than an array of strings.
    final parsed = generatePagination.map((e) => jsonDecode(e)).toList();
    final encoded = jsonEncode(parsed);

    // Inject the array into the outer response body template.
    return Interpolation().excute(
      before: responseBody,
      data: encoded,
      request: request,
    );
  }
}
